### ISSUE TITLE
Some issues with H5PP on Mac

### ISSUE THREAD

**Issue by gayverjr** [DavidAce/h5pp#12] opened 2022-04-04 14:22 UTC
Hi DavidAce,
I've been trying to migrate to the latest version of H5PP (previously I was pinned to v1.7.3), and I've been running into some issues that maybe you can help with.

The first comes when I try to include H5PP in my CMake project. I added it using `FetchContent_Declare`, and set `-DH5PP_ENABLE_EIGEN3=ON` at the cmake step. When I try to compile (tried using both GCC and AppleClang) I get the following error:

`/Users/jamesrgayvert/Documents/work/opencap/opencap/opencap/build/_deps/h5pp-src/include/h5pp/details/h5ppEigen.h:122:72: error: no member named 'runtime_error' in namespace 'h5pp'`

I also tried just cloning H5PP and building it from source. The error I get here is curious, as for whatever reason H5PP does not like the HDF5 1.12.1 that was installed on my machine by homebrew.  I ran just a simple CMake with no extra options and I get:

`-- HDF5 Package disqualified: 1.12.1 /opt/homebrew/Cellar/hdf5/1.12.1/include;/opt/homebrew/opt/szip/include
             Reason: HDF5 static libraries depends on a shared library and no static replacement was found: z;dl;m `

I also tried with an HDF5 installed by conda, and set the HDF5_ROOT environment variable to $CONDA_PREFIX and passing -DHDF5_DIR=$CONDA_PREFIX to cmake, and it kept trying the homebrew installation and failing no matter what I did.

I would appreciate any tips/suggestions!

**Comment by DavidAce** [comment] 2022-04-04 15:19
Hi! Thanks for reporting this issue.
First of all, I have made improvements to the installation process since the last release, which are in the master branch. I'll include these changes in a future release of h5pp 1.10. With some luck, the master branch works and you could try pinning a commit for the time being. 

I can see now that my macos builds on GitHub Actions are set up to install their own HDF5 from source, rather than using the version from brew. Probably I ran in to a similar issue with the one from brew at some point. The HDF5 versions from conda always gave me headaches with linkage errors so I've stopped supporting it. I haven't tried it lately though.

For the first error message: I can see in my git log that I had indeed forgotten to `#include "h5ppError.h"` at the top of `h5ppEigen.h`. This was fixed in e6e939307442412f743adfc923468f6a07868d07, which is after 1.9.0, I think.

For the second message: This error is generated by the version of FindHDF5.cmake that is bundled with h5pp. The point of it is to avoid injection of shared libraries in static builds. It seems like the HDF5 version from homebrew depends on shared/dynamic versions of zlib, libdl, and libm libraries. 
There are a couple of possible solutions one could consider:
- link shared libraries (with `-DBUILD_SHARED_LIBS=ON`), or
- don't use the HDF5 from brew (or conda for that matter), but install HDF5 from source, or
- delete the h5pp bundled file `FindHDF5.cmake` file, so that `find_package(HDF5...)` will call the original one bundled with CMake instead (at the risk of mixing static/shared libraries), or
- perhaps one could install static versions of these libraries? (not sure how this works on mac)

The mixing of static/shared libraries is not a big deal for most use cases, it's just that I've been using h5pp on a heterogeneous HPC cluster where linking everything statically is important. Perhaps I should relax these checks...

My top recommendation would be to use conan to handle the dependencies. This the simplest and most reliable procedure. See the [quickstart](https://github.com/DavidAce/h5pp/tree/master/quickstart) examples for different ways of using conan. Conan will also install libraries like zlib transitively with correct linkage.

If you prefer a fetch-content like approach you could also give [cpm](https://github.com/cpm-cmake/CPM.cmake) a try, with CMake option `H5PP_PACKAGE_MANAGER=cpm`. Of course you can use cpm from your own project instead and set `H5PP_PACKAGE_MANAGER=find` (which is the default). 

Let me know if any of this works, or else we can take it from there.

**Comment by gayverjr** [comment] 2022-04-04 16:07
Unfortunately, I'm not sure that the missing include was the problem for the first error message.

I am running fetch_content with `GIT_TAG 68369425955323707bf2130b73e9190108183136`, aka, the latest commit at time of writing, and I've double checked and that the include is present in h5ppEigen.h.
<img width="444" alt="Screen Shot 2022-04-04 at 10 55 58 AM" src="https://user-images.githubusercontent.com/29463611/161583726-65f3c1b5-7390-4285-9851-5a05fabab0f4.png">

As for the second error, fetching with conan does seem to work fine at the CMake step. I cloned the repo, and then ran cmake with:
`cmake -DH5PP_PACKAGE_MANAGER=conan -DCMAKE_BUILD_TYPE=debug -DH5PP_BUILD_EXAMPLES=ON -DH5PP_ENABLE_EIGEN3=ON .. `

And then when I `make` a familiar friend appears:
`/home/gayverjr/h5pp_install/h5pp/include/h5pp/details/h5ppEigen.h:50:58: error: ‘runtime_error’ is not a member of ‘h5pp’
                 if(container.size() != rank) throw h5pp::runtime_error("copy_dims: Wrong container size, can't copy dimensions.");`

I have been testing this on both my Mac OS (with GCC-11 and AppleClang V13) and on our HPC cluster with GCC 8.3.0, and I am getting the same errors.

**Comment by DavidAce** [comment] 2022-04-04 16:26
Ah, interesting. I'll investigate. Just to make sure: is the second error also on the latest commit?

**Comment by gayverjr** [comment] 2022-04-04 16:29
Correct, the second error is on the latest commit.

**Comment by DavidAce** [comment] 2022-04-04 16:35
Could you please attach here a file with the CMake output? To get more info add `--loglevel=DEBUG`  as well as `-DCMAKE_VERBOSE_MAKEFILE=ON` to the CMake step

**Comment by gayverjr** [comment] 2022-04-04 16:42
[cmake_output.txt](https://github.com/DavidAce/h5pp/files/8411568/cmake_output.txt)
[CMakeCache.txt](https://github.com/DavidAce/h5pp/files/8411569/CMakeCache.txt)

**Comment by DavidAce** [comment] 2022-04-04 17:27
I found the issue. It turns out there was an issue with circular includes of headers, which would only manifest when spdlog wasn't enabled. I didn't notice because I've had it enabled lately. I should probably add a test for for that. The problem is now fixed in master branch, in any case. I also updated hdf5 to 1.12.1

By the way, when spdlog is not enabled, h5pp falls back to a less performant hand-crafted logger which uses streams. The log messages should be identical though. I really recommend enabling spdlog both for reduced runtime and compile time.

Let me know how it goes!

**Comment by gayverjr** [comment] 2022-04-04 17:55
Alright, I can confirm that compiling H5PP with and without spdlog now works, and I can also confirm that the latest commit works now with my package without spdlog. I need to do some of my own testing to figure out how exactly I want to integrate things (e.g. whether to use H5PP to download things or just get the pieces I want myself), but I will definitely be looking into that sometime later in the week. Thanks a lot for your help!

**Closed** 2022-04-17 07:51 UTC
